This is makeindex, version 2.16 [MiKTeX 25.3].
Scanning style file ./EE-dyplom.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file EE-dyplom.acn....done (5 entries accepted, 0 rejected).
Sorting entries....done (15 comparisons).
Generating output file EE-dyplom.acr....done (17 lines written, 0 warnings).
Output written in EE-dyplom.acr.
Transcript written in EE-dyplom.alg.
